### ISSUE TITLE
No artists being displayed

### ISSUE THREAD

**Issue by Rudd-O** [jtbgroup/kodi-media-sensors#19]
I search for an artist I know Kodi has, because Chorus shows it.

The TCPDUMP shows the artist is being returned:

```
#......-W3.8P...&....~..{"id":"51a379f9-cca6-46e5-9e15-b223058b5920","jsonrpc":"2.0","result":{"artists":[{"artist":"Ace of Base","artistid":29,"genre":[],"label":"Ace of Base","mood":[],"style":[],"thumbnail":"image://%2fvar%2fshared%2fEntertainment%2fMusic%2fGood%2fAlbums%20and%20singles%2fAce%20of%20Base%2fcover.jpg/"},{"artist":"Rico Bernasconi Vs Ace of Base","artistid":6496,"genre":[],"label":"Rico Bernasconi Vs Ace of Base","mood":[],"style":[],"thumbnail":""},{"artist":"Rico Bernasconi VS. Ace Of Base","artistid":6152,"genre":[],"label":"Rico Bernasconi VS. Ace Of Base","mood":[],"style":[],"thumbnail":""}],"limits":{"end":3,"start":0,"total":3}}}
```

Nonetheless, the artist is not displayed in the card.

If you believe this is an issue with the Kodi Search Card instead, please let me know!

**Comment by jtbgroup** [comment]
Hi,

Strange as I have no issue with this functionality as you can see:
![Screenshot_20220903_071815](https://user-images.githubusercontent.com/10096931/188256996-f21b5389-8ea0-4097-89a6-84c80ef892b2.png)

Integration Kodi Media Sensors version must be 3.5.0
Frontend Kodi Search Card version must be 3.2.1

Did you check the Developer Tools to see the content of the sensor called `sensor.kodi_media_sensor_search`?
Did you check the configuration of the integration? There are some checkboxes related to the artists. Because I had to rename some options, it might be that the old option names are no longer available and the integration takes the default values.

If still nothing is displayed, can you give me your search keyword?

Regards,

**Comment by Rudd-O** [comment]
You are right.
