### ISSUE TITLE
Format Search Results For "upcoming-media-card"

### ISSUE THREAD

**Issue by Andrewdlec** [jtbgroup/kodi-media-sensors#24]
Is it possible to have the results from a movie/TVshows search be formatted the same way the results for recently added movies and TV shows are formatted. In order to use the "upcoming-media-card" the results must include the format: 

Component needs an attribute named "data" that contains a JSON string or OBJ.
The first item in your JSON must contain these keys to set your defaults: title_default, line1_default, line2_default, line3_default, line4_default, and icon. The default text contents are set exactly like the card's text content config and use the same keywords. The default icon takes an mdi icon mdi:arrow-down.
Each item must contain an 'airdate', if none exists the item is skipped. This and a poster image are the only required items.
If an included item is null it needs to be an empty string in the JSON ''.
Items should be in descending order according to 'airdate'.
Be aware that the card strips parentheses and anything contained in them. This is to remove things like (US). Since we can see the art for the show/movie there is no need for that info.

The recently added movies and TV show sensors format this way by default and if the search sensor did too, the results from the search could also be displayed in the "upcoming-media-card".

Thanks!

**Comment by jtbgroup** [comment]
Hi,

No, I won't do that because I want a standard result for the different sensors (search and playlist). I kept the compatibility with the requirements of this card for the 2 other sensors, but actually, I don't understand those requirements. It's a non sense to me to return a resultset containing some layout information. And using the metadata attribute allows me to pass some parameters needed for the sensors. 

But you can ask the developers of this card to change their code :smile: 

Regards

**Comment by Andrewdlec** [comment]
I was able to get it working with some modifications to the media sensors file. What I was/did trying to accomplish is the ability to select a letter from the alphabet.. A, B, C.. etc and have any movie that starts with that letter return in the results. I have a lot of movies and returning a result of all movies was very slow to return and required a LOT of scrolling. lol. Thank for your getting back to me so quickly!
