### ISSUE TITLE
Not working in HA 2023.x

### ISSUE THREAD

**Issue by Stooovie** [jtbgroup/kodi-media-sensors#27]
**Describe the bug**
Weird sensors with names such as "sensor.kms_t_23cee762cab760b43a2f4faa604cddc7" are created and do not display any incoming data.

**Screenshots**

![Screenshot 2023-03-06 at 15 40 31](https://user-images.githubusercontent.com/10572373/223142508-264bec4f-86b3-4441-813a-5ead05f3e953.jpg)

**Home Assistant and Custom Component versions (please complete the following information):**
Home Assistant version: 2023.3.2
kodi-recently-added component version: 5.0.1

**Additional context**
Tried re-downloading 5.0.1 from HACS, didn't fix the issue.

**Comment by jtbgroup** [comment]
Hi Stoovie,

This is normal. It comes from the enhancement [26](https://github.com/jtbgroup/kodi-media-sensors/issues/26) allowing to have multiple instances of the media sensors. Unique ID's are needed for that. But you can still change the entity name and the entity ID in HA.

That's why I added a special mention in the release note.

**Comment by Stooovie** [comment]
Right! Search wasn't working for me at first, that's why I filed this report. But it eventually started to work. Consider this closed and thank you!

**Comment by jtbgroup** [comment]
Great, thanks for your feedback.
